# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Yik Jiun"

# URL
baseurl:            "/blog"
rooturl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "Blog"
    href:           ""
  - name:           "About"
    href:           "//www.yikjiun.com/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

var_read: Read # Text after each post summary on the homepage.
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read # Text after reading time. Example: 5 min read.

# Build settings
markdown: kramdown
